image : node:14.18.1 # editable node version to match one's own node version for deployment

stages :
  - build
  - deploy

services:
  - mysql:latest

cache :
  paths :
    - node_modules/

build-pages:
  stage : build
  script :
    - npm config set proxy "http://cache.univ-st-etienne.fr:3128"
    - rm -rf build
    - CI=false npm install
    - CI=false npm run build
    - CI=false npm install -g serve
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
    - serve -s build
  artifacts:
    paths:
      - public


pages:
  stage: deploy
  script:
    - ls
  artifacts:
    paths:
      - public

      
