image : node:14.18.1 # editable node version to match one's own node version for deployment

stages: 
  - build
  - test
  - deploy

build:
  stage: build
  image: node:14.18.1
  script:
    - echo "building the app"
    - npm install
    - npm build
    - echo "app has been built successfully"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test:
  stage:  test
  image: node:14.18.1
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "the test has been successful"

deploy:
  stage: deploy
  script:
    - echo "deploying the app"
    - npm install -g serve
    - serve -s build
