# image : node:latest # editable node version to match one's own node version for deployment

# stages :
#   - build
#   - deploy

# services:
#   - mysql:latest

# cache :
#   paths :
#     - node_modules/

# build-pages:
#   stage : build
#   script :
#     - rm -rf build
#     - CI=false npm install
#     - CI=false npm run build
#     - rm -rf public
#     - cp # add the files here to build 
#     - mv build public

#   artifacts:
#     paths:
#       - public


# pages:
#   stage: deploy
#   script:
#     - ls
#   artifacts:
#     paths:
#       - public

      
